/**
 * Prompt Injection Protection
 * Sanitizes user input for LLM consumption
 */

/**
 * Dangerous patterns that could lead to prompt injection
 */
const DANGEROUS_PATTERNS = [
  /ignore previous instructions/gi,
  /forget everything/gi,
  /system prompt/gi,
  /secret instructions/gi,
  /roleplay as/gi,
  /pretend you are/gi,
  /act as if/gi,
  /disregard all/gi,
]

/**
 * Prompt boundary markers to prevent injection
 */
const PROMPT_BOUNDARY = {
  start: '--- USER INPUT START ---',
  end: '--- USER INPUT END ---',
}

interface SanitizeOptions {
  maxLength?: number
  allowInjectionWarnings?: boolean
}

/**
 * Sanitize user input for LLM safety
 * - Removes dangerous patterns
 * - Enforces length limits
 * - Adds prompt boundaries
 * - Escapes special characters
 */
export function sanitizePrompt(
  input: string,
  options: SanitizeOptions = {}
): string {
  const { maxLength = 2000, allowInjectionWarnings = true } = options

  // Trim whitespace
  let sanitized = input.trim()

  // Check length
  if (sanitized.length > maxLength) {
    sanitized = sanitized.substring(0, maxLength).trim()
  }

  // Check for injection patterns
  let hasInjectionAttempt = false
  for (const pattern of DANGEROUS_PATTERNS) {
    if (pattern.test(sanitized)) {
      hasInjectionAttempt = true
      // Remove the dangerous pattern
      sanitized = sanitized.replace(pattern, '')
    }
  }

  // Log injection attempts
  if (hasInjectionAttempt && allowInjectionWarnings) {
    console.warn('Potential prompt injection detected and sanitized', {
      original: input.substring(0, 100),
      timestamp: new Date().toISOString(),
    })
  }

  // Add prompt boundaries
  const boundedPrompt = `${PROMPT_BOUNDARY.start}\n${sanitized}\n${PROMPT_BOUNDARY.end}`

  return boundedPrompt
}

/**
 * Validate that input is safe for interview prep context
 * Restricts to reasonable topics only
 */
export function validateInterviewPrepInput(input: string): {
  valid: boolean
  error?: string
} {
  const maxLength = 5000
  const minLength = 10

  if (input.length < minLength) {
    return {
      valid: false,
      error: 'Input is too short. Provide at least 10 characters.',
    }
  }

  if (input.length > maxLength) {
    return {
      valid: false,
      error: `Input is too long. Maximum ${maxLength} characters allowed.`,
    }
  }

  // Check for code injection attempts
  const codePatterns = [
    /eval\(/gi,
    /exec\(/gi,
    /system\(/gi,
    /__.*__/g,
    /require\(/gi,
    /import\s+/gi,
  ]

  for (const pattern of codePatterns) {
    if (pattern.test(input)) {
      return {
        valid: false,
        error: 'Input contains potentially unsafe content.',
      }
    }
  }

  return { valid: true }
}

/**
 * Sanitize user feedback/notes for storage
 * Prevents XSS when displayed
 */
export function sanitizeUserFeedback(feedback: string): string {
  // Remove HTML tags
  let sanitized = feedback.replace(/<[^>]*>/g, '')

  // Escape special characters
  sanitized = sanitized
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#x27;')

  return sanitized.trim()
}

/**
 * Check if content appears to be generated by an LLM
 * Useful for validating responses haven't been manipulated
 */
export function validateLLMBoundaries(content: string): boolean {
  return (
    content.includes(PROMPT_BOUNDARY.start) &&
    content.includes(PROMPT_BOUNDARY.end)
  )
}
